import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784141002940 implements MigrationInterface {
    name = 'InitialSchema1784141002940'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'underwriter', 'claims_officer', 'finance', 'compliance', 'broker', 'customer', 'readonly')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'pending_verification')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'readonly', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "phone" character varying(20), "mfaEnabled" boolean NOT NULL DEFAULT false, "mfaSecret" character varying, "lastLogin" TIMESTAMP, "failedLoginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "refreshToken" character varying, "passwordResetToken" character varying, "passwordResetExpiry" TIMESTAMP, "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "emailVerificationExpiry" TIMESTAMP, "branchId" character varying(100), "department" character varying(100), "preferences" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fdf5f552fcfe06082a35e9728" ON "users" ("refreshToken") `);
        await queryRunner.query(`CREATE TYPE "public"."weather_trigger_events_status_enum" AS ENUM('detected', 'payouts_calculated', 'claims_created', 'settled', 'review_required')`);
        await queryRunner.query(`CREATE TABLE "weather_trigger_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventRef" character varying(30) NOT NULL, "stationId" character varying(50) NOT NULL, "productId" character varying NOT NULL, "triggerDate" date NOT NULL, "measurementPeriodStart" date NOT NULL, "measurementPeriodEnd" date NOT NULL, "triggerType" character varying(50) NOT NULL, "measuredValue" numeric(10,3) NOT NULL, "thresholdValue" numeric(10,3) NOT NULL, "payoutLevel" character varying(50) NOT NULL, "payoutPercentage" numeric(5,2) NOT NULL, "status" "public"."weather_trigger_events_status_enum" NOT NULL DEFAULT 'detected', "affectedPolicyCount" integer NOT NULL DEFAULT '0', "totalPayoutAmount" numeric(18,2) NOT NULL DEFAULT '0', "affectedPolicyIds" jsonb, "generatedClaimIds" jsonb, "reviewedById" character varying(36), "reviewedAt" TIMESTAMP, "reviewNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3c60c554e8477cd772d04287d14" UNIQUE ("eventRef"), CONSTRAINT "PK_19d8d004b1ec459dd714bd04127" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c60c554e8477cd772d04287d1" ON "weather_trigger_events" ("eventRef") `);
        await queryRunner.query(`CREATE INDEX "IDX_31628e73421a78ba753aeef021" ON "weather_trigger_events" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_769c60b48bdfa17f5279f3867c" ON "weather_trigger_events" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."weather_readings_metric_enum" AS ENUM('rainfall_mm', 'temperature_c', 'soil_moisture_pct', 'drought_index')`);
        await queryRunner.query(`CREATE TABLE "weather_readings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stationId" character varying(50) NOT NULL, "readingDate" date NOT NULL, "metric" "public"."weather_readings_metric_enum" NOT NULL, "value" numeric(10,3) NOT NULL, "source" character varying(50), "isAnomaly" boolean NOT NULL DEFAULT false, "rawPayload" jsonb, "ingestedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4b0af2443f5cfa5a2dbfc31ffc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e95f5964ec41c5c0933e26683" ON "weather_readings" ("stationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_795912f969f773cc8a63768043" ON "weather_readings" ("readingDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0028790c031ef2be1676bd51fd" ON "weather_readings" ("stationId", "readingDate", "metric") `);
        await queryRunner.query(`CREATE TYPE "public"."products_type_enum" AS ENUM('credit_life', 'health', 'personal_all_risks', 'agriculture_weather_index', 'travel')`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('draft', 'active', 'suspended', 'discontinued')`);
        await queryRunner.query(`CREATE TYPE "public"."products_phase_enum" AS ENUM('phase_1', 'phase_2')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(30) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "type" "public"."products_type_enum" NOT NULL, "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft', "phase" "public"."products_phase_enum" NOT NULL DEFAULT 'phase_1', "premiumRules" jsonb NOT NULL, "coverageConfig" jsonb NOT NULL, "underwritingRules" jsonb, "weatherIndexConfig" jsonb, "allowedDistributionChannels" text, "isBrokerSellable" boolean NOT NULL DEFAULT true, "brokerCommissionRate" numeric(5,2) NOT NULL DEFAULT '0', "isPortalSellable" boolean NOT NULL DEFAULT true, "createdById" character varying(36), "lastModifiedById" character varying(36), "activatedAt" TIMESTAMP, "ipecDetails" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7cfc24d6c24f0ec91294003d6b8" UNIQUE ("code"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cfc24d6c24f0ec91294003d6b" ON "products" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."customers_type_enum" AS ENUM('individual', 'corporate')`);
        await queryRunner.query(`CREATE TYPE "public"."customers_segment_enum" AS ENUM('retail', 'sme', 'corporate', 'broker_client', 'micro', 'agricultural')`);
        await queryRunner.query(`CREATE TYPE "public"."customers_status_enum" AS ENUM('active', 'inactive', 'suspended', 'deceased', 'blacklisted')`);
        await queryRunner.query(`CREATE TYPE "public"."customers_kycstatus_enum" AS ENUM('not_submitted', 'pending_review', 'approved', 'rejected', 'expired', 're_verification_required')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerNumber" character varying(20) NOT NULL, "type" "public"."customers_type_enum" NOT NULL DEFAULT 'individual', "firstName" character varying(100), "lastName" character varying(100), "dateOfBirth" date, "gender" character varying(10), "idNumber" character varying(20), "passportNumber" character varying(20), "passportExpiry" TIMESTAMP, "companyName" character varying(255), "registrationNumber" character varying(50), "taxNumber" character varying(50), "industryType" character varying(100), "email" character varying(255) NOT NULL, "phone" character varying(20), "whatsappNumber" character varying(20), "alternatePhone" character varying(20), "addressLine1" character varying(255), "addressLine2" character varying(255), "city" character varying(100), "province" character varying(100), "country" character varying(100) NOT NULL DEFAULT 'Zimbabwe', "postalCode" character varying(20), "segment" "public"."customers_segment_enum" NOT NULL DEFAULT 'retail', "status" "public"."customers_status_enum" NOT NULL DEFAULT 'active', "kycStatus" "public"."customers_kycstatus_enum" NOT NULL DEFAULT 'not_submitted', "kycApprovedAt" TIMESTAMP, "kycExpiryDate" TIMESTAMP, "isPep" boolean NOT NULL DEFAULT false, "isSanctioned" boolean NOT NULL DEFAULT false, "riskRating" character varying(50), "brokerId" character varying, "userId" character varying, "emailNotifications" boolean NOT NULL DEFAULT true, "smsNotifications" boolean NOT NULL DEFAULT true, "whatsappNotifications" boolean NOT NULL DEFAULT false, "preferredLanguage" character varying(10), "notes" text, "createdById" character varying(36), "assignedOfficerId" character varying(36), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ac2fd5d477df162f3f6246c7284" UNIQUE ("customerNumber"), CONSTRAINT "UQ_b8512aa9cef03d90ed5744c94d7" UNIQUE ("userId"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac2fd5d477df162f3f6246c728" ON "customers" ("customerNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_023c77aa1c88b5d7bdba05ec5c" ON "customers" ("idNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_8536b8b85c06969f84f0c098b0" ON "customers" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8512aa9cef03d90ed5744c94d" ON "customers" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b65af7b37fa9ec8b88f5f5baee" ON "customers" ("idNumber") WHERE "idNumber" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."policies_status_enum" AS ENUM('quotation', 'pending_payment', 'active', 'lapsed', 'cancelled', 'expired', 'renewed', 'suspended', 'claimed')`);
        await queryRunner.query(`CREATE TYPE "public"."policies_currency_enum" AS ENUM('USD', 'ZIG', 'ZAR', 'GBP')`);
        await queryRunner.query(`CREATE TYPE "public"."policies_underwritingdecision_enum" AS ENUM('auto_approved', 'referred', 'pending', 'approved', 'declined')`);
        await queryRunner.query(`CREATE TYPE "public"."policies_distributionchannel_enum" AS ENUM('direct_staff', 'broker', 'customer_portal', 'mobile_app', 'whatsapp')`);
        await queryRunner.query(`CREATE TABLE "policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "policyNumber" character varying(30) NOT NULL, "customerId" uuid NOT NULL, "productId" uuid NOT NULL, "status" "public"."policies_status_enum" NOT NULL DEFAULT 'quotation', "sumInsured" numeric(18,2) NOT NULL, "annualPremium" numeric(18,2) NOT NULL, "netPremium" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL DEFAULT '0', "levyAmount" numeric(18,2) NOT NULL DEFAULT '0', "grossPremium" numeric(18,2) NOT NULL, "currency" "public"."policies_currency_enum" NOT NULL DEFAULT 'USD', "startDate" date, "endDate" date, "expiryDate" date, "issueDate" TIMESTAMP, "cancellationDate" TIMESTAMP, "cancellationReason" text, "cancellationRefundAmount" numeric(18,2), "underwritingDecision" "public"."policies_underwritingdecision_enum" NOT NULL DEFAULT 'pending', "underwriterId" character varying(36), "underwritingDate" TIMESTAMP, "underwritingNotes" text, "riskScore" numeric(5,2), "riskData" jsonb, "distributionChannel" "public"."policies_distributionchannel_enum" NOT NULL DEFAULT 'direct_staff', "brokerId" character varying(36), "agentId" character varying(36), "brokerCommission" numeric(18,2) NOT NULL DEFAULT '0', "beneficiaries" jsonb, "renewedFromPolicyId" character varying(36), "renewedToPolicyId" character varying(36), "renewalCount" integer NOT NULL DEFAULT '1', "scheduleDocumentKey" character varying, "certificateDocumentKey" character varying, "scheduleGeneratedAt" TIMESTAMP, "outstandingPremium" numeric(18,2) NOT NULL DEFAULT '0', "lastPaymentDate" TIMESTAMP, "nextPaymentDueDate" TIMESTAMP, "createdById" character varying(36), "coverageDetails" jsonb, "endorsementHistory" jsonb, "version" integer NOT NULL DEFAULT '1', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a8802538a5b1523552e79d49c7d" UNIQUE ("policyNumber"), CONSTRAINT "PK_603e09f183df0108d8695c57e28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a8802538a5b1523552e79d49c7" ON "policies" ("policyNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_e34db8f7611187a907c9dc878a" ON "policies" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3312cfd8348cc306b8b4293fff" ON "policies" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_851c01a7b92d518b40cb816cc4" ON "policies" ("startDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_b71b0a3cc8b1541e7b7956482a" ON "policies" ("endDate") `);
        await queryRunner.query(`CREATE TYPE "public"."policy_endorsements_type_enum" AS ENUM('sum_insured_increase', 'sum_insured_decrease', 'beneficiary_change', 'address_change', 'coverage_extension', 'coverage_reduction', 'reinstatement', 'correction', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."policy_endorsements_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'rejected', 'applied')`);
        await queryRunner.query(`CREATE TABLE "policy_endorsements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endorsementNumber" character varying(30) NOT NULL, "policyId" uuid NOT NULL, "type" "public"."policy_endorsements_type_enum" NOT NULL, "status" "public"."policy_endorsements_status_enum" NOT NULL DEFAULT 'draft', "effectiveDate" date NOT NULL, "previousState" jsonb NOT NULL, "newState" jsonb NOT NULL, "additionalPremium" numeric(18,2) NOT NULL DEFAULT '0', "premiumRefund" numeric(18,2) NOT NULL DEFAULT '0', "reason" text, "requestedById" character varying(36), "approvedById" character varying(36), "approvedAt" TIMESTAMP, "documentKey" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2b17fa5254f36454a6dbe8124d6" UNIQUE ("endorsementNumber"), CONSTRAINT "PK_c80273f35f70da2e8eb92cfd2e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86ba51a4323084339861dae00f" ON "policy_endorsements" ("policyId") `);
        await queryRunner.query(`CREATE TYPE "public"."commission_statements_status_enum" AS ENUM('draft', 'issued', 'queried', 'paid')`);
        await queryRunner.query(`CREATE TABLE "commission_statements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "statementNumber" character varying(30) NOT NULL, "brokerId" character varying NOT NULL, "period" character varying(7) NOT NULL, "lineItems" jsonb NOT NULL, "totalCommission" numeric(18,2) NOT NULL, "status" "public"."commission_statements_status_enum" NOT NULL DEFAULT 'issued', "queryNotes" text, "paidAt" TIMESTAMP, "paymentRef" character varying(50), "documentKey" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_18b7d368cfa4a40bcb4988e2b16" UNIQUE ("statementNumber"), CONSTRAINT "PK_a13cdb260d1d99f86a712b49bef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_61419e5cbf7f642ae7e7c2772f" ON "commission_statements" ("brokerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_da8c3693124fa1521398047c15" ON "commission_statements" ("brokerId", "period") `);
        await queryRunner.query(`CREATE TYPE "public"."brokers_type_enum" AS ENUM('individual_agent', 'corporate_broker', 'bancassurance')`);
        await queryRunner.query(`CREATE TYPE "public"."brokers_status_enum" AS ENUM('active', 'suspended', 'terminated', 'pending_accreditation')`);
        await queryRunner.query(`CREATE TABLE "brokers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "brokerCode" character varying(20) NOT NULL, "name" character varying(200) NOT NULL, "type" "public"."brokers_type_enum" NOT NULL DEFAULT 'individual_agent', "email" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "ipecLicenseNumber" character varying(50), "licenseExpiryDate" TIMESTAMP, "status" "public"."brokers_status_enum" NOT NULL DEFAULT 'pending_accreditation', "userId" character varying(36), "bankAccountDetails" character varying(255), "mobileMoneyNumber" character varying(20), "defaultCommissionRate" numeric(5,2) NOT NULL DEFAULT '0', "totalCommissionEarned" numeric(18,2) NOT NULL DEFAULT '0', "totalCommissionPaid" numeric(18,2) NOT NULL DEFAULT '0', "outstandingCommission" numeric(18,2) NOT NULL DEFAULT '0', "accreditedAt" TIMESTAMP, "accreditedById" character varying(36), "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_554767187c89678a7c9704c04d8" UNIQUE ("brokerCode"), CONSTRAINT "PK_b8ee0411488131f6f9d322dbe7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_554767187c89678a7c9704c04d" ON "brokers" ("brokerCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_2e0851305a0577dffe07182f23" ON "brokers" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."reinsurance_treaties_type_enum" AS ENUM('quota_share', 'surplus', 'excess_of_loss', 'facultative')`);
        await queryRunner.query(`CREATE TYPE "public"."reinsurance_treaties_status_enum" AS ENUM('active', 'expired', 'terminated', 'draft')`);
        await queryRunner.query(`CREATE TABLE "reinsurance_treaties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "treatyRef" character varying(30) NOT NULL, "name" character varying(200) NOT NULL, "reinsurerName" character varying(200) NOT NULL, "reinsurerContact" character varying(100), "type" "public"."reinsurance_treaties_type_enum" NOT NULL, "status" "public"."reinsurance_treaties_status_enum" NOT NULL DEFAULT 'draft', "effectiveDate" date NOT NULL, "expiryDate" date NOT NULL, "cessionPercentage" numeric(5,2), "retentionLimit" numeric(18,2), "maxCessionLimit" numeric(18,2), "cedingCommissionRate" numeric(5,2) NOT NULL DEFAULT '0', "flatAnnualPremium" numeric(18,2), "applicableProductTypes" text, "terms" text, "createdById" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0ae16961ac8ca350160dddb2c3a" UNIQUE ("treatyRef"), CONSTRAINT "PK_fde60b7155867d8302c7a0569f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ae16961ac8ca350160dddb2c3" ON "reinsurance_treaties" ("treatyRef") `);
        await queryRunner.query(`CREATE TYPE "public"."reinsurance_recoveries_status_enum" AS ENUM('pending', 'claimed_from_reinsurer', 'received', 'disputed')`);
        await queryRunner.query(`CREATE TABLE "reinsurance_recoveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "claimId" character varying NOT NULL, "claimNumber" character varying(30) NOT NULL, "treatyId" character varying NOT NULL, "cessionId" character varying, "grossClaimAmount" numeric(18,2) NOT NULL, "recoverableAmount" numeric(18,2) NOT NULL, "recoveredAmount" numeric(18,2) NOT NULL DEFAULT '0', "status" "public"."reinsurance_recoveries_status_enum" NOT NULL DEFAULT 'pending', "claimedAt" TIMESTAMP, "receivedAt" TIMESTAMP, "bordereauPeriod" character varying(7), "glPosted" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86c615eac12007b5440c7d2b71a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c7e346550a34be8a534816a0a4" ON "reinsurance_recoveries" ("claimId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4208fb61e42370b53e42310651" ON "reinsurance_recoveries" ("treatyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9d9c726a69d25876668668e3d1" ON "reinsurance_recoveries" ("status") `);
        await queryRunner.query(`CREATE TABLE "reinsurance_cessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "policyId" character varying NOT NULL, "policyNumber" character varying(30) NOT NULL, "treatyId" character varying NOT NULL, "grossSumInsured" numeric(18,2) NOT NULL, "cededSumInsured" numeric(18,2) NOT NULL, "retainedSumInsured" numeric(18,2) NOT NULL, "grossPremium" numeric(18,2) NOT NULL, "cededPremium" numeric(18,2) NOT NULL, "retainedPremium" numeric(18,2) NOT NULL, "cedingCommission" numeric(18,2) NOT NULL DEFAULT '0', "cessionRatio" numeric(5,4) NOT NULL, "bordereauPeriod" character varying(7), "glPosted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_066909f1033e6f7f65b4f23fee5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5dfa46443adeef83de26bedfb1" ON "reinsurance_cessions" ("policyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3c2e073e25aea228ad4a57431" ON "reinsurance_cessions" ("treatyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c151e85dc6950a7920b454d807" ON "reinsurance_cessions" ("policyId", "treatyId") `);
        await queryRunner.query(`CREATE TYPE "public"."reinsurance_bordereaux_status_enum" AS ENUM('draft', 'issued', 'acknowledged', 'settled')`);
        await queryRunner.query(`CREATE TABLE "reinsurance_bordereaux" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bordereauNumber" character varying(30) NOT NULL, "treatyId" character varying NOT NULL, "period" character varying(7) NOT NULL, "premiumCessions" jsonb NOT NULL, "claimRecoveries" jsonb NOT NULL, "totalCededPremium" numeric(18,2) NOT NULL, "totalCedingCommission" numeric(18,2) NOT NULL, "totalRecoveries" numeric(18,2) NOT NULL, "netDueToReinsurer" numeric(18,2) NOT NULL, "status" "public"."reinsurance_bordereaux_status_enum" NOT NULL DEFAULT 'draft', "issuedAt" TIMESTAMP, "settledAt" TIMESTAMP, "settlementRef" character varying(50), "documentKey" character varying, "generatedById" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1cc2f4c02c26c7e5a14a6ac21ce" UNIQUE ("bordereauNumber"), CONSTRAINT "PK_c0a6cdc0b24c93c13b66af2bc6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e3f42b806de6ec94f140c78b80" ON "reinsurance_bordereaux" ("treatyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3041a4575dd4e302638c393a3e" ON "reinsurance_bordereaux" ("treatyId", "period") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_paymenttype_enum" AS ENUM('premium_collection', 'claim_settlement', 'commission_payment', 'refund', 'reinsurance_premium')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_channel_enum" AS ENUM('ecocash', 'onemoney', 'innbucks', 'bank_transfer', 'rtgs', 'zipit', 'swift', 'card', 'cash')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('initiated', 'pending', 'success', 'failed', 'reversed', 'queued', 'timed_out')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "paymentRef" character varying(40) NOT NULL, "paymentType" "public"."payments_paymenttype_enum" NOT NULL, "channel" "public"."payments_channel_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'initiated', "amount" numeric(18,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'USD', "fxRate" numeric(12,6) NOT NULL DEFAULT '1', "baseCurrencyAmount" numeric(18,2) NOT NULL, "policyId" character varying(36), "invoiceId" character varying(36), "claimId" character varying(36), "customerId" character varying(36), "gatewayRef" character varying(100), "gatewayOrderId" character varying(100), "gatewayRequest" jsonb, "gatewayResponse" jsonb, "payerPhone" character varying(30), "payerAccountNumber" character varying(50), "payerName" character varying(100), "confirmedAt" TIMESTAMP, "retryCount" integer NOT NULL DEFAULT '0', "nextRetryAt" TIMESTAMP, "failureReason" text, "glPosted" boolean NOT NULL DEFAULT false, "glJournalRef" character varying(50), "processedById" character varying(36), "reversalOfPaymentId" character varying(36), "metadata" jsonb, "initiatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0195e1ffe15ff56475334393ae0" UNIQUE ("paymentRef"), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0195e1ffe15ff56475334393ae" ON "payments" ("paymentRef") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_90113bfa209ce2021d3c464824" ON "payments" ("gatewayRef") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfab1486d0514029f6b5e6a53e" ON "payments" ("initiatedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_invoicetype_enum" AS ENUM('new_business', 'renewal', 'endorsement', 'additional_premium')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled', 'written_off')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying(30) NOT NULL, "policyId" uuid NOT NULL, "customerId" uuid NOT NULL, "invoiceType" "public"."invoices_invoicetype_enum" NOT NULL DEFAULT 'new_business', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'issued', "netPremium" numeric(18,2) NOT NULL, "taxAmount" numeric(18,2) NOT NULL DEFAULT '0', "levyAmount" numeric(18,2) NOT NULL DEFAULT '0', "totalAmount" numeric(18,2) NOT NULL, "paidAmount" numeric(18,2) NOT NULL DEFAULT '0', "outstandingAmount" numeric(18,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'USD', "dueDate" date NOT NULL, "paidDate" TIMESTAMP, "cancelledDate" TIMESTAMP, "notes" text, "issuedById" character varying(36), "glPosted" boolean NOT NULL DEFAULT false, "glPostedAt" TIMESTAMP, "glJournalRef" character varying(36), "sentToCustomerAt" TIMESTAMP, "lineItems" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bf8e0f9dd4558ef209ec111782d" UNIQUE ("invoiceNumber"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bf8e0f9dd4558ef209ec111782" ON "invoices" ("invoiceNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_41ee6a6636d48aac700fb52e0b" ON "invoices" ("dueDate") `);
        await queryRunner.query(`CREATE TYPE "public"."gl_accounts_type_enum" AS ENUM('asset', 'liability', 'equity', 'revenue', 'expense')`);
        await queryRunner.query(`CREATE TYPE "public"."gl_accounts_category_enum" AS ENUM('cash', 'bank', 'mobile_money', 'accounts_receivable', 'premium_receivable', 'reinsurance_recoverable', 'fixed_assets', 'accumulated_depreciation', 'investment', 'accounts_payable', 'claims_payable', 'claims_reserve', 'unearned_premium', 'reinsurance_payable', 'tax_payable', 'gross_written_premium', 'reinsurance_premium', 'investment_income', 'claims_incurred', 'commission_expense', 'operating_expense', 'management_expense')`);
        await queryRunner.query(`CREATE TABLE "gl_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(20) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "type" "public"."gl_accounts_type_enum" NOT NULL, "category" "public"."gl_accounts_category_enum" NOT NULL, "parentCode" character varying(20), "costCentre" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "isSystemAccount" boolean NOT NULL DEFAULT false, "currentBalance" numeric(18,2) NOT NULL DEFAULT '0', "currency" character varying(10), "createdById" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dbac2467bb68b5a45ac898599ac" UNIQUE ("code"), CONSTRAINT "PK_aca57e576cc505f791703da1b32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dbac2467bb68b5a45ac898599a" ON "gl_accounts" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."gl_entries_source_enum" AS ENUM('premium_receipt', 'claim_reserve', 'claim_payment', 'commission_accrual', 'commission_payment', 'bank_reconciliation', 'manual_journal', 'reinsurance_cession', 'reinsurance_recovery', 'depreciation', 'tax_payment', 'currency_revaluation', 'opening_balance')`);
        await queryRunner.query(`CREATE TABLE "gl_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "journalRef" character varying(50) NOT NULL, "accountId" uuid NOT NULL, "accountCode" character varying(20), "accountName" character varying(255), "debit" numeric(18,2) NOT NULL DEFAULT '0', "credit" numeric(18,2) NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'USD', "fxRate" numeric(12,6) NOT NULL DEFAULT '1', "baseCurrencyDebit" numeric(18,2) NOT NULL DEFAULT '0', "baseCurrencyCredit" numeric(18,2) NOT NULL DEFAULT '0', "source" "public"."gl_entries_source_enum" NOT NULL, "sourceId" character varying(36), "sourceRef" character varying(50), "description" character varying(500), "costCentre" character varying(50), "postedById" character varying(36), "approvedById" character varying(100), "isReversed" boolean NOT NULL DEFAULT false, "reversalOfEntryId" character varying(36), "period" character varying(50), "metadata" jsonb, "postedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9dd59adceb57450ca518ecebe23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dcd54acf2c12fd38c8f900fc91" ON "gl_entries" ("journalRef") `);
        await queryRunner.query(`CREATE INDEX "IDX_488a82e0554026ce4b3d4d961b" ON "gl_entries" ("postedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_d064e49cd582c8b1a3a06d14f9" ON "gl_entries" ("accountId", "postedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."fixed_assets_category_enum" AS ENUM('it_equipment', 'office_furniture', 'motor_vehicle', 'building', 'leasehold_improvement', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."fixed_assets_depreciationmethod_enum" AS ENUM('straight_line', 'reducing_balance')`);
        await queryRunner.query(`CREATE TYPE "public"."fixed_assets_status_enum" AS ENUM('active', 'disposed', 'fully_depreciated', 'written_off')`);
        await queryRunner.query(`CREATE TABLE "fixed_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "assetCode" character varying(20) NOT NULL, "description" character varying(255) NOT NULL, "category" "public"."fixed_assets_category_enum" NOT NULL, "acquisitionDate" date NOT NULL, "cost" numeric(18,2) NOT NULL, "residualValue" numeric(18,2) NOT NULL DEFAULT '0', "usefulLifeMonths" integer NOT NULL, "depreciationMethod" "public"."fixed_assets_depreciationmethod_enum" NOT NULL DEFAULT 'straight_line', "reducingBalanceRate" numeric(5,2), "accumulatedDepreciation" numeric(18,2) NOT NULL DEFAULT '0', "netBookValue" numeric(18,2) NOT NULL, "status" "public"."fixed_assets_status_enum" NOT NULL DEFAULT 'active', "location" character varying(100), "custodian" character varying(100), "lastDepreciationRunDate" TIMESTAMP, "disposalDate" TIMESTAMP, "disposalProceeds" numeric(18,2), "disposalNotes" text, "createdById" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_74c89027d520edff4dcc8d66deb" UNIQUE ("assetCode"), CONSTRAINT "PK_901984c25ddf1dcf11f1c7a70d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74c89027d520edff4dcc8d66de" ON "fixed_assets" ("assetCode") `);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_status_enum" AS ENUM('open', 'in_progress', 'pending_customer', 'resolved', 'closed', 'escalated')`);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_category_enum" AS ENUM('policy_query', 'claims_query', 'payment_issue', 'kyc_issue', 'portal_issue', 'complaint', 'general')`);
        await queryRunner.query(`CREATE TABLE "support_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketNumber" character varying(25) NOT NULL, "customerId" character varying NOT NULL, "subject" character varying(500) NOT NULL, "description" text NOT NULL, "status" "public"."support_tickets_status_enum" NOT NULL DEFAULT 'open', "priority" "public"."support_tickets_priority_enum" NOT NULL DEFAULT 'medium', "category" "public"."support_tickets_category_enum" NOT NULL DEFAULT 'general', "assignedToId" character varying(36), "policyId" character varying(36), "claimId" character varying(36), "slaDeadline" TIMESTAMP, "resolvedAt" TIMESTAMP, "closedAt" TIMESTAMP, "escalatedAt" TIMESTAMP, "escalatedToId" character varying(36), "slaBreach" boolean NOT NULL DEFAULT false, "resolution" text, "comments" jsonb, "createdById" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6e4c71fa5e96520463e92aa02d9" UNIQUE ("ticketNumber"), CONSTRAINT "PK_942e8d8f5df86100471d2324643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e4c71fa5e96520463e92aa02d" ON "support_tickets" ("ticketNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_ee952666931bd353d113acdd5d" ON "support_tickets" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba7b1a2ed4051fb3b39ff95444" ON "support_tickets" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."leads_stage_enum" AS ENUM('new', 'contacted', 'qualified', 'quoted', 'converted', 'lost')`);
        await queryRunner.query(`CREATE TYPE "public"."leads_source_enum" AS ENUM('walk_in', 'referral', 'broker', 'website', 'social_media', 'cold_call', 'campaign', 'other')`);
        await queryRunner.query(`CREATE TABLE "leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leadNumber" character varying(20) NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "companyName" character varying(255), "email" character varying(255) NOT NULL, "phone" character varying(20), "stage" "public"."leads_stage_enum" NOT NULL DEFAULT 'new', "source" "public"."leads_source_enum" NOT NULL DEFAULT 'other', "productInterest" character varying(100), "estimatedPremium" numeric(18,2), "assignedToId" character varying(36), "brokerId" character varying(36), "convertedCustomerId" character varying(36), "convertedAt" TIMESTAMP, "nextFollowUpDate" TIMESTAMP, "notes" text, "lostReason" text, "createdById" character varying(36), "campaignRef" character varying(100), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cf1c749625dea29bd7ac0d33932" UNIQUE ("leadNumber"), CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf1c749625dea29bd7ac0d3393" ON "leads" ("leadNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3eea7add0e16594dba102716c" ON "leads" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_77f3ccbdd78ea7032d8cec382d" ON "leads" ("stage") `);
        await queryRunner.query(`CREATE TYPE "public"."kyc_documents_documenttype_enum" AS ENUM('national_id', 'passport', 'drivers_license', 'utility_bill', 'bank_statement', 'company_certificate', 'tax_clearance', 'proof_of_address', 'directors_list', 'cr14')`);
        await queryRunner.query(`CREATE TYPE "public"."kyc_documents_status_enum" AS ENUM('pending', 'approved', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "kyc_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "documentType" "public"."kyc_documents_documenttype_enum" NOT NULL, "documentNumber" character varying(100), "fileKey" character varying NOT NULL, "fileUrl" character varying(500), "fileExtension" character varying(10), "fileSizeBytes" integer, "status" "public"."kyc_documents_status_enum" NOT NULL DEFAULT 'pending', "expiryDate" TIMESTAMP, "reviewedAt" TIMESTAMP, "reviewedById" character varying(36), "rejectionReason" text, "isVirusScanned" boolean NOT NULL DEFAULT false, "virusFlagged" boolean NOT NULL DEFAULT false, "version" integer NOT NULL DEFAULT '1', "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_02e49877f1578e6285f84e57ab6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d56b4deb5797ba5c475ceef56" ON "kyc_documents" ("customerId") `);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_channel_enum" AS ENUM('email', 'sms', 'whatsapp', 'phone_call', 'in_person', 'portal_message', 'push_notification')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_direction_enum" AS ENUM('outbound', 'inbound')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_purpose_enum" AS ENUM('policy_renewal_reminder', 'payment_receipt', 'payment_reminder', 'policy_issued', 'claim_acknowledgement', 'claim_update', 'claim_settled', 'kyc_reminder', 'kyc_approved', 'kyc_rejected', 'otp', 'general', 'marketing', 'welcome', 'password_reset', 'endorsement', 'cancellation')`);
        await queryRunner.query(`CREATE TYPE "public"."communication_logs_status_enum" AS ENUM('pending', 'sent', 'delivered', 'read', 'failed', 'bounced')`);
        await queryRunner.query(`CREATE TABLE "communication_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" uuid NOT NULL, "channel" "public"."communication_logs_channel_enum" NOT NULL, "direction" "public"."communication_logs_direction_enum" NOT NULL DEFAULT 'outbound', "purpose" "public"."communication_logs_purpose_enum" NOT NULL DEFAULT 'general', "subject" character varying(500), "body" text, "recipient" character varying(20), "status" "public"."communication_logs_status_enum" NOT NULL DEFAULT 'pending', "externalMessageId" character varying(100), "deliveredAt" TIMESTAMP, "readAt" TIMESTAMP, "errorMessage" text, "sentById" character varying(36), "policyId" character varying, "claimId" character varying, "metadata" jsonb, "sentAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d20f31e44aa2108bd47d7a6f781" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4992b11665bf79df55c6afde4d" ON "communication_logs" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_75153aa7623a56facf430c3eb4" ON "communication_logs" ("sentAt") `);
        await queryRunner.query(`CREATE TYPE "public"."claims_status_enum" AS ENUM('fnol_submitted', 'registered', 'under_assessment', 'pending_documents', 'referred_to_senior', 'approved', 'partially_approved', 'rejected', 'settlement_processing', 'settled', 'closed', 'withdrawn', 'fraud_investigation')`);
        await queryRunner.query(`CREATE TYPE "public"."claims_claimtype_enum" AS ENUM('death', 'permanent_disability', 'temporary_disability', 'medical_inpatient', 'medical_outpatient', 'property_loss', 'property_damage', 'weather_trigger', 'travel_cancellation', 'medical_evacuation', 'baggage_loss')`);
        await queryRunner.query(`CREATE TYPE "public"."claims_channel_enum" AS ENUM('web_portal', 'mobile_app', 'call_centre', 'broker_portal', 'walk_in', 'email', 'system_automated')`);
        await queryRunner.query(`CREATE TABLE "claims" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "claimNumber" character varying(30) NOT NULL, "policyId" uuid NOT NULL, "customerId" uuid NOT NULL, "status" "public"."claims_status_enum" NOT NULL DEFAULT 'fnol_submitted', "claimType" "public"."claims_claimtype_enum" NOT NULL, "channel" "public"."claims_channel_enum" NOT NULL DEFAULT 'web_portal', "eventDate" date NOT NULL, "eventDescription" text, "eventLocation" character varying(255), "claimedAmount" numeric(18,2), "reserveAmount" numeric(18,2) NOT NULL DEFAULT '0', "approvedAmount" numeric(18,2), "settlementAmount" numeric(18,2), "currency" character varying(10), "excess" numeric(18,2) NOT NULL DEFAULT '0', "fraudScore" numeric(5,2) NOT NULL DEFAULT '0', "fraudFlagged" boolean NOT NULL DEFAULT false, "fraudFlags" text, "duplicateDetected" boolean NOT NULL DEFAULT false, "assignedToId" character varying(36), "assessedById" character varying(36), "assessmentDate" TIMESTAMP, "assessmentNotes" text, "approvedById" character varying(36), "approvalDate" TIMESTAMP, "rejectionReason" text, "settlementDate" TIMESTAMP, "settlementPaymentRef" character varying(50), "settlementPaymentChannel" character varying(20), "settlementAccountNumber" character varying(100), "reserveGlPosted" boolean NOT NULL DEFAULT false, "settlementGlPosted" boolean NOT NULL DEFAULT false, "thirdPartyDetails" jsonb, "serviceProviderDetails" jsonb, "submittedById" character varying(36), "acknowledgedAt" TIMESTAMP, "slaTargetDate" TIMESTAMP, "slaBreachedAt" TIMESTAMP, "statusHistory" jsonb, "metadata" jsonb, "fnolDate" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae47a48242e9feaa7e202e344c9" UNIQUE ("claimNumber"), CONSTRAINT "PK_96c91970c0dcb2f69fdccd0a698" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae47a48242e9feaa7e202e344c" ON "claims" ("claimNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_cea536bf1c443b4d4c207a436f" ON "claims" ("policyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8003b148efab49dd30f8bb2516" ON "claims" ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_78214f7ed47cfd76fb8bf6bb28" ON "claims" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."claim_documents_documenttype_enum" AS ENUM('death_certificate', 'medical_certificate', 'police_report', 'hospital_invoice', 'assessor_report', 'photo_evidence', 'id_document', 'claim_form', 'supporting_affidavit', 'weather_data', 'prescription', 'lab_results', 'other')`);
        await queryRunner.query(`CREATE TABLE "claim_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "claimId" uuid NOT NULL, "documentType" "public"."claim_documents_documenttype_enum" NOT NULL, "originalFilename" character varying(255), "fileKey" character varying NOT NULL, "fileExtension" character varying(10), "fileSizeBytes" integer, "isVirusScanned" boolean NOT NULL DEFAULT false, "virusFlagged" boolean NOT NULL DEFAULT false, "uploadedById" character varying(36), "notes" text, "version" integer NOT NULL DEFAULT '1', "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_926ac9a44ec173769f00b65b841" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_718164d7fb5ba51d93bb07d716" ON "claim_documents" ("claimId") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'login', 'logout', 'login_failed', 'password_change', 'role_change', 'approve', 'reject', 'export', 'view_sensitive', 'system')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "entityType" character varying(100), "entityId" character varying(36), "entityRef" character varying(100), "userId" character varying(36), "userEmail" character varying(100), "userRole" character varying(50), "before" jsonb, "after" jsonb, "changes" jsonb, "description" character varying(500), "ipAddress" character varying(50), "userAgent" character varying(500), "requestId" character varying(100), "module" character varying(20), "metadata" jsonb, "performedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_57680dda80b2d5c8967f2b50af" ON "audit_logs" ("performedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e68d9afd30e5d8a379486388c" ON "audit_logs" ("userId", "performedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_sessions_status_enum" AS ENUM('active', 'ended', 'escalated')`);
        await queryRunner.query(`CREATE TABLE "chat_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" character varying NOT NULL, "userId" character varying(36), "status" "public"."chat_sessions_status_enum" NOT NULL DEFAULT 'active', "messages" jsonb NOT NULL DEFAULT '[]', "escalatedToTicketId" character varying(36), "messageCount" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efc151a4aafa9a28b73dedc485f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac59aa703b8a9ca1bef2f47039" ON "chat_sessions" ("customerId") `);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "FK_e34db8f7611187a907c9dc878a3" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policies" ADD CONSTRAINT "FK_6c10643df2991a365c297d7f283" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "policy_endorsements" ADD CONSTRAINT "FK_86ba51a4323084339861dae00fb" FOREIGN KEY ("policyId") REFERENCES "policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_91161bc3e2586990c6dd9e1615d" FOREIGN KEY ("policyId") REFERENCES "policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_1df049f8943c6be0c1115541efb" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gl_entries" ADD CONSTRAINT "FK_1cb27da85923fb4a683dde416ee" FOREIGN KEY ("accountId") REFERENCES "gl_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kyc_documents" ADD CONSTRAINT "FK_7d56b4deb5797ba5c475ceef56f" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communication_logs" ADD CONSTRAINT "FK_4992b11665bf79df55c6afde4da" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claims" ADD CONSTRAINT "FK_cea536bf1c443b4d4c207a436fd" FOREIGN KEY ("policyId") REFERENCES "policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claims" ADD CONSTRAINT "FK_8003b148efab49dd30f8bb2516e" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "claim_documents" ADD CONSTRAINT "FK_718164d7fb5ba51d93bb07d7168" FOREIGN KEY ("claimId") REFERENCES "claims"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "claim_documents" DROP CONSTRAINT "FK_718164d7fb5ba51d93bb07d7168"`);
        await queryRunner.query(`ALTER TABLE "claims" DROP CONSTRAINT "FK_8003b148efab49dd30f8bb2516e"`);
        await queryRunner.query(`ALTER TABLE "claims" DROP CONSTRAINT "FK_cea536bf1c443b4d4c207a436fd"`);
        await queryRunner.query(`ALTER TABLE "communication_logs" DROP CONSTRAINT "FK_4992b11665bf79df55c6afde4da"`);
        await queryRunner.query(`ALTER TABLE "kyc_documents" DROP CONSTRAINT "FK_7d56b4deb5797ba5c475ceef56f"`);
        await queryRunner.query(`ALTER TABLE "gl_entries" DROP CONSTRAINT "FK_1cb27da85923fb4a683dde416ee"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_1df049f8943c6be0c1115541efb"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_91161bc3e2586990c6dd9e1615d"`);
        await queryRunner.query(`ALTER TABLE "policy_endorsements" DROP CONSTRAINT "FK_86ba51a4323084339861dae00fb"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "FK_6c10643df2991a365c297d7f283"`);
        await queryRunner.query(`ALTER TABLE "policies" DROP CONSTRAINT "FK_e34db8f7611187a907c9dc878a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac59aa703b8a9ca1bef2f47039"`);
        await queryRunner.query(`DROP TABLE "chat_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."chat_sessions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e68d9afd30e5d8a379486388c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57680dda80b2d5c8967f2b50af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_718164d7fb5ba51d93bb07d716"`);
        await queryRunner.query(`DROP TABLE "claim_documents"`);
        await queryRunner.query(`DROP TYPE "public"."claim_documents_documenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78214f7ed47cfd76fb8bf6bb28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8003b148efab49dd30f8bb2516"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cea536bf1c443b4d4c207a436f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae47a48242e9feaa7e202e344c"`);
        await queryRunner.query(`DROP TABLE "claims"`);
        await queryRunner.query(`DROP TYPE "public"."claims_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."claims_claimtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."claims_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75153aa7623a56facf430c3eb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4992b11665bf79df55c6afde4d"`);
        await queryRunner.query(`DROP TABLE "communication_logs"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communication_logs_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d56b4deb5797ba5c475ceef56"`);
        await queryRunner.query(`DROP TABLE "kyc_documents"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."kyc_documents_documenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77f3ccbdd78ea7032d8cec382d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3eea7add0e16594dba102716c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf1c749625dea29bd7ac0d3393"`);
        await queryRunner.query(`DROP TABLE "leads"`);
        await queryRunner.query(`DROP TYPE "public"."leads_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leads_stage_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba7b1a2ed4051fb3b39ff95444"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee952666931bd353d113acdd5d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e4c71fa5e96520463e92aa02d"`);
        await queryRunner.query(`DROP TABLE "support_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74c89027d520edff4dcc8d66de"`);
        await queryRunner.query(`DROP TABLE "fixed_assets"`);
        await queryRunner.query(`DROP TYPE "public"."fixed_assets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fixed_assets_depreciationmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fixed_assets_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d064e49cd582c8b1a3a06d14f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_488a82e0554026ce4b3d4d961b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcd54acf2c12fd38c8f900fc91"`);
        await queryRunner.query(`DROP TABLE "gl_entries"`);
        await queryRunner.query(`DROP TYPE "public"."gl_entries_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbac2467bb68b5a45ac898599a"`);
        await queryRunner.query(`DROP TABLE "gl_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."gl_accounts_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."gl_accounts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ee6a6636d48aac700fb52e0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf8e0f9dd4558ef209ec111782"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_invoicetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfab1486d0514029f6b5e6a53e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90113bfa209ce2021d3c464824"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0195e1ffe15ff56475334393ae"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_paymenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3041a4575dd4e302638c393a3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3f42b806de6ec94f140c78b80"`);
        await queryRunner.query(`DROP TABLE "reinsurance_bordereaux"`);
        await queryRunner.query(`DROP TYPE "public"."reinsurance_bordereaux_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c151e85dc6950a7920b454d807"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3c2e073e25aea228ad4a57431"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5dfa46443adeef83de26bedfb1"`);
        await queryRunner.query(`DROP TABLE "reinsurance_cessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d9c726a69d25876668668e3d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4208fb61e42370b53e42310651"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7e346550a34be8a534816a0a4"`);
        await queryRunner.query(`DROP TABLE "reinsurance_recoveries"`);
        await queryRunner.query(`DROP TYPE "public"."reinsurance_recoveries_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ae16961ac8ca350160dddb2c3"`);
        await queryRunner.query(`DROP TABLE "reinsurance_treaties"`);
        await queryRunner.query(`DROP TYPE "public"."reinsurance_treaties_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reinsurance_treaties_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e0851305a0577dffe07182f23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_554767187c89678a7c9704c04d"`);
        await queryRunner.query(`DROP TABLE "brokers"`);
        await queryRunner.query(`DROP TYPE "public"."brokers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."brokers_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da8c3693124fa1521398047c15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61419e5cbf7f642ae7e7c2772f"`);
        await queryRunner.query(`DROP TABLE "commission_statements"`);
        await queryRunner.query(`DROP TYPE "public"."commission_statements_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86ba51a4323084339861dae00f"`);
        await queryRunner.query(`DROP TABLE "policy_endorsements"`);
        await queryRunner.query(`DROP TYPE "public"."policy_endorsements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."policy_endorsements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b71b0a3cc8b1541e7b7956482a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_851c01a7b92d518b40cb816cc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3312cfd8348cc306b8b4293fff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e34db8f7611187a907c9dc878a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8802538a5b1523552e79d49c7"`);
        await queryRunner.query(`DROP TABLE "policies"`);
        await queryRunner.query(`DROP TYPE "public"."policies_distributionchannel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."policies_underwritingdecision_enum"`);
        await queryRunner.query(`DROP TYPE "public"."policies_currency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."policies_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b65af7b37fa9ec8b88f5f5baee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8512aa9cef03d90ed5744c94d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8536b8b85c06969f84f0c098b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_023c77aa1c88b5d7bdba05ec5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac2fd5d477df162f3f6246c728"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_kycstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customers_segment_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customers_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cfc24d6c24f0ec91294003d6b"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_phase_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0028790c031ef2be1676bd51fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_795912f969f773cc8a63768043"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e95f5964ec41c5c0933e26683"`);
        await queryRunner.query(`DROP TABLE "weather_readings"`);
        await queryRunner.query(`DROP TYPE "public"."weather_readings_metric_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_769c60b48bdfa17f5279f3867c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31628e73421a78ba753aeef021"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c60c554e8477cd772d04287d1"`);
        await queryRunner.query(`DROP TABLE "weather_trigger_events"`);
        await queryRunner.query(`DROP TYPE "public"."weather_trigger_events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fdf5f552fcfe06082a35e9728"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
