export default () => ({
  app: {
    name: process.env.APP_NAME || 'EBA EIMP',
    env: process.env.NODE_ENV || 'development',
    port: parseInt(process.env.PORT || '3001', 10),
    apiPrefix: 'api/v1',
    jwtSecret: process.env.JWT_SECRET || 'dev-secret-change-in-production',
    jwtExpiry: process.env.JWT_EXPIRY || '15m',
    jwtRefreshExpiry: process.env.JWT_REFRESH_EXPIRY || '7d',
    encryptionKey: process.env.ENCRYPTION_KEY || 'dev-encryption-key-32-characters',
    adminPortalUrl: process.env.ADMIN_PORTAL_URL || 'http://localhost:3000',
    customerPortalUrl: process.env.CUSTOMER_PORTAL_URL || 'http://localhost:3002',
  },
  database: {
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5432', 10),
    name: process.env.DB_NAME || process.env.POSTGRES_DB || 'eimp_db',
    username: process.env.DB_USER || process.env.POSTGRES_USER || 'eimp_user',
    password: process.env.DB_PASSWORD || process.env.POSTGRES_PASSWORD || 'eimp_secure_password',
    synchronize: process.env.NODE_ENV !== 'production',
    logging: process.env.NODE_ENV === 'development',
  },
  redis: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379', 10),
    password: process.env.REDIS_PASSWORD || 'redis_secure_password',
  },
  aws: {
    region: process.env.AWS_REGION || 'af-south-1',
    s3Bucket: process.env.AWS_S3_BUCKET || 'eimp-documents',
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || '',
    cloudfrontDomain: process.env.AWS_CLOUDFRONT_DOMAIN || '',
  },
  email: {
    sesRegion: process.env.SES_REGION || 'af-south-1',
    fromEmail: process.env.SES_FROM_EMAIL || 'noreply@ebamicroinsurance.co.zw',
    fromName: process.env.SES_FROM_NAME || 'EBA Micro Insurance',
    smtpHost: process.env.SMTP_HOST || '',
    smtpPort: parseInt(process.env.SMTP_PORT || '587', 10),
    smtpUser: process.env.SMTP_USER || '',
    smtpPass: process.env.SMTP_PASS || '',
  },
  sms: {
    provider: process.env.SMS_PROVIDER || 'twilio',
    twilioSid: process.env.TWILIO_ACCOUNT_SID || '',
    twilioToken: process.env.TWILIO_AUTH_TOKEN || '',
    twilioPhone: process.env.TWILIO_PHONE_NUMBER || '',
    econetApiUrl: process.env.ECONET_SMS_API_URL || '',
    econetApiKey: process.env.ECONET_SMS_API_KEY || '',
  },
  payments: {
    ecocash: {
      apiUrl: process.env.ECOCASH_API_URL || '',
      merchantCode: process.env.ECOCASH_MERCHANT_CODE || '',
      apiKey: process.env.ECOCASH_API_KEY || '',
      apiSecret: process.env.ECOCASH_API_SECRET || '',
    },
    onemoney: {
      apiUrl: process.env.ONEMONEY_API_URL || '',
      apiKey: process.env.ONEMONEY_API_KEY || '',
      merchantNumber: process.env.ONEMONEY_MERCHANT_NUMBER || '',
    },
    innbucks: {
      apiUrl: process.env.INNBUCKS_API_URL || '',
      apiKey: process.env.INNBUCKS_API_KEY || '',
      merchantId: process.env.INNBUCKS_MERCHANT_ID || '',
    },
  },
  weather: {
    apiUrl: process.env.WEATHER_API_URL || '',
    apiKey: process.env.WEATHER_API_KEY || '',
  },
  ai: {
    anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
    anthropicApiUrl: process.env.ANTHROPIC_API_URL || 'https://api.anthropic.com/v1/messages',
    anthropicModel: process.env.ANTHROPIC_MODEL || 'claude-sonnet-4-6',
    anthropicMaxTokens: parseInt(process.env.ANTHROPIC_MAX_TOKENS || '1024', 10),
  },
  whatsapp: {
    apiUrl: process.env.WHATSAPP_API_URL || '',
    apiKey: process.env.WHATSAPP_API_KEY || '',
    phoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID || '',
  },
});
